name: Tests and linting

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  selenium:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox']

    name: "Selenium - ${{ matrix.browser }}"

    services:
      selenium-hub:
        image: selenium/hub:4.0.0-beta-1-20210215
        options: >-
          --health-cmd "/opt/bin/check-grid.sh"
        ports:
          - 4444:4444

      # Start one instance of Chrome
      selenium-node-chrome:
        image: selenium/node-chrome:4.0.0-beta-1-20210215
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

      # Start two instances of Firefox
      selenium-node-firefox-1:
        image: selenium/node-firefox:4.0.0-beta-1-20210215
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      selenium-node-firefox-2:
        image: selenium/node-firefox:4.0.0-beta-1-20210215
        volumes:
          - /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, zip

      - name: Install dependencies
        run: composer update --no-progress

      - name: Run Steward
        run: vendor/bin/steward run production ${{ matrix.browser }} -vvv

      - name: Print results
        run: vendor/bin/steward results -vvv

      - name: Generate timeline.html
        run: vendor/bin/steward generate-timeline

      - name: Upload logs and screenshots
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: logs (Selenium - ${{ matrix.browser }})
          path: ${{ github.workspace }}/logs/*
          retention-days: 1

      - name: Print services logs
        if: ${{ success() || failure() }}
        run: |
          echo --- selenium-hub ---
          docker logs "${{ job.services.selenium-hub.id }}"
          echo --- selenium-node-chrome ---
          docker logs "${{ job.services.selenium-node-chrome.id }}"
          echo --- selenium-node-firefox-1 ---
          docker logs "${{ job.services.selenium-node-firefox-1.id }}"
          echo --- selenium-node-firefox-2 ---
          docker logs "${{ job.services.selenium-node-firefox-2.id }}"

  codestyle:
    name: "Code style and static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl

      - name: Install dependencies
        run: composer update --no-progress

      - name: Lint
        run: composer lint

      - name: Run checks
        run: composer analyze
